# Generated by Django 4.0.3 on 2023-06-09 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0012_alter_automobilevo_sold_alter_automobilevo_vin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='price',
            field=models.TextField(null=True),
        ),
    ]
